version: "2"
services:
  app:
    image: node:latest
    command: "npm start"
    restart: unless-stopped
    working_dir: /app
    links:
      - mail
      - db
    environment:
      - NODE_ENV=production
      - NODE_CONFIG_ENV=docker
    volumes:
      - .:/app
    ports:
      - "3001:80"

  mail:
    image: node:latest
    command: "npm run mail-server"
    restart: unless-stopped
    working_dir: /app
    links:
      - db
    environment:
      - NODE_ENV=production
      - NODE_CONFIG_ENV=docker
    volumes:
      - .:/app
    expose:
      - 25
    ports:
      - "25:25"

  db:
    image: rethinkdb:latest
    restart: unless-stopped
    volumes:
      - ./db:/data
    expose:
      - 28015
    ports:
      - "8080:8080"
      - "28015:28015"
